
SET SQL DIALECT 3; 

/* CREATE DATABASE 'C:\ProjetoFortes\PostoABC\Banco\Postoabc.fdb' PAGE_SIZE 4096 DEFAULT CHARACTER SET NONE */



/* Table: ABASTECIMENTO, Owner: SYSDBA */
CREATE TABLE ABASTECIMENTO (CODIGO_ABASTECIMENTO INTEGER NOT NULL,
        DATA_ABASTECIMENTO DATE NOT NULL,
        CODIGO_BOMBA INTEGER NOT NULL,
        LITROS DECIMAL(10, 2) NOT NULL,
        VALOR_TOTAL DECIMAL(10, 2) NOT NULL,
        IMPOSTO COMPUTED BY (VALOR_TOTAL * 0.13),
PRIMARY KEY (CODIGO_ABASTECIMENTO));

/* Table: BOMBA, Owner: SYSDBA */
CREATE TABLE BOMBA (CODIGO_BOMBA INTEGER NOT NULL,
        DESCRICAO_BOMBA VARCHAR(50) NOT NULL,
        CODIGO_TANQUE INTEGER NOT NULL,
PRIMARY KEY (CODIGO_BOMBA));

/* Table: TANQUE, Owner: SYSDBA */
CREATE TABLE TANQUE (CODIGO_TANQUE INTEGER NOT NULL,
        DESCRICAO VARCHAR(50) NOT NULL,
        TIPO_COMBUSTIVEL CHAR(1) NOT NULL,
PRIMARY KEY (CODIGO_TANQUE));

ALTER TABLE ABASTECIMENTO ADD FOREIGN KEY (CODIGO_BOMBA) REFERENCES BOMBA (CODIGO_BOMBA);

ALTER TABLE BOMBA ADD FOREIGN KEY (CODIGO_TANQUE) REFERENCES TANQUE (CODIGO_TANQUE);
